conditions: v1
dist: xenial

git:
  depth: 100

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
    - $HOME/.pre-commit
    - $HOME/virtualenv/python$(python -c 'import platform; print(platform.python_version())')
    - $HOME/Library/Caches/Homebrew

language: python

jobs:
  fast_finish: true

  include:
    - python: "3.6"
      name: Running linters
      env:
        TOXENV: linters

install:
  - pip install -U tox virtualenv  # newer virtualenv has newer pip inside
  - tox --notest  # Pre-populate virtualenv

script:
  - tox -v
