name: tox

on:
  create:  # is used for publishing to PyPI and TestPyPI
    tags:  # any tag regardless of its name, no branches
  push:  # only publishes pushes to the main branch to TestPyPI
    branches:  # any integration branch but not tag
      - "master"
    tags-ignore:
      - "**"
  pull_request:
  schedule:
    - cron: 1 0 * * *  # Run daily at 0:01 UTC

jobs:
  make:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: sanity
          - name: units
          - name: integration
          - name: coverage
    steps:
      - uses: actions/checkout@v1
      - name: Run workarounds github-action specific
        # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
        run: |
          sudo apt-get -qq -y remove --purge ansible
          mkdir -p ~/.local/bin
          export PATH=$HOME/.local/bin:$PATH
          # remove ansible 2.9 which comes free on github actions
          # assure we have a pip with decent resolver
          python3 -m pip install "pip>=20.3.1"
          # lets fix some already missing dependencies from gha ubuntu image
          pip3 install launchpadlib pygobject
          # lets see the goodies...
          pip3 check
          # to bring pip installed stuff in user PATH, for *subsequent* runs
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Run make devenv
        run: |
          echo "PATH=$PATH"
          make devenv
      - name: Run make install
        run: |
          make install
          make ${{ matrix.name }}

  tox:
    name: ${{ matrix.tox_env }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - tox_env: lint
          # TODO(ssbarnea): replace molecule env with default once molecule
          # will be able to install collection being tested:
          # https://github.com/ansible-community/molecule/pull/2998
          - tox_env: molecule
          - tox_env: sanity
          - tox_env: units

    steps:
      - uses: actions/checkout@v1
      - name: Install system dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install -y libvirt-dev
      - name: Find python version
        id: py_ver
        shell: python
        if: ${{ contains(matrix.tox_env, 'py') }}
        run: |
          v = '${{ matrix.tox_env }}'.split('-')[0].lstrip('py')
          print('::set-output name=version::{0}.{1}'.format(v[0],v[1:]))
      # Even our lint and other envs need access to tox
      - name: Install a default Python
        uses: actions/setup-python@v2
        # workaround to avoid getting 3.9 in:
        with:
          python-version: '3.8'
        if: ${{ ! contains(matrix.tox_env, 'py') }}
      # Be sure to install the version of python needed by a specific test, if necessary
      - name: Set up Python version
        uses: actions/setup-python@v2
        if: ${{ contains(matrix.tox_env, 'py') }}
        with:
          python-version: ${{ steps.py_ver.outputs.version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install tox
      - name: Run tox -e ${{ matrix.tox_env }}
        run: |
          echo "${{ matrix.PREFIX }} tox -e ${{ matrix.tox_env }}"
          ${{ matrix.PREFIX }} tox -e ${{ matrix.tox_env }}

  publish:
    name: Publish to PyPI registry
    needs:
      - tox
      - make
    runs-on: ubuntu-latest

    env:
      PY_COLORS: 1
      TOXENV: packaging

    steps:
      - name: Switch to using Python 3.6 by default
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install tox
        run: python -m pip install --user tox
      - name: Check out src from Git
        uses: actions/checkout@v2
        with:
          # Get shallow Git history (default) for tag creation events
          # but have a complete clone for any other workflows.
          # Both options fetch tags but since we're going to remove
          # one from HEAD in non-create-tag workflows, we need full
          # history for them.
          fetch-depth: >-
            ${{
              (
                github.event_name == 'create' &&
                github.event.ref_type == 'tag'
              ) &&
              1 || 0
            }}
      - name: Drop Git tags from HEAD for non-tag-create events
        if: >-
          github.event_name != 'create' ||
          github.event.ref_type != 'tag'
        run: >-
          git tag --points-at HEAD
          |
          xargs git tag --delete
      - name: Build dists
        run: python -m tox
      - name: Publish to test.pypi.org
        if: >-
          (
            github.event_name == 'push' &&
            github.ref == format(
              'refs/heads/{0}', github.event.repository.default_branch
            )
          ) ||
          (
            github.event_name == 'create' &&
            github.event.ref_type == 'tag'
          )
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.testpypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish to pypi.org
        if: >-  # "create" workflows run separately from "push" & "pull_request"
          github.event_name == 'create' &&
          github.event.ref_type == 'tag'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
# No need to publish to quay.io from here as they do it when a new tag
# is pushed on git.
